// app-solid/src/App.jsx
import { createSignal } from "solid-js";
import { Settings } from "./pages/Settings";
import { Integrations } from "./pages/Integrations";
import "./App.css";

function App() {
  const [currentPage, setCurrentPage] = createSignal("settings");

  const renderPage = () => {
    switch (currentPage()) {
      case "settings":
        return <Settings />;
      case "integrations":
        return <Integrations />;
      default:
        return <Settings />;
    }
  };

  return (
    <div class="app-solid">
      {/* Navigation */}
      <nav class="app-nav">
        <div class="nav-brand">
          <svg class="nav-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          <span class="nav-title">Settings Hub</span>
        </div>
        <div class="nav-links">
          <button
            class={`nav-link ${currentPage() === "settings" ? "active" : ""}`}
            onClick={() => setCurrentPage("settings")}
          >
            <svg class="nav-link-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            Settings
          </button>
          <button
            class={`nav-link ${currentPage() === "integrations" ? "active" : ""}`}
            onClick={() => setCurrentPage("integrations")}
          >
            <svg class="nav-link-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z" />
            </svg>
            Integrations
          </button>
        </div>
      </nav>

      {/* Page Content */}
      <main class="app-content">
        {renderPage()}
      </main>
    </div>
  );
}

export default App;

// app-react-1/src/App.jsx
import React from "react";
import { BrowserRouter, Routes, Route, Link, Navigate, useLocation } from "react-router";
import { Home } from "./pages/Home";
import { Users } from "./pages/Users";
import { UserDetail, UserProfile, UserActivity, UserPermissions, UserSettings } from "./pages/UserDetail";
import "./App.css";

const AppNav = () => {
  const location = useLocation();

  const isActive = (path) => {
    if (path === "/") {
      return location.pathname === "/" || (!location.pathname.includes("/"));
    }
    return location.pathname.startsWith(path);
  };

  return (
    <nav className="app-nav">
      <div className="nav-brand">
        <svg className="nav-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
        </svg>
        <span className="nav-title">User Management</span>
      </div>
      <div className="nav-links">
        <Link
          to="/"
          className={`nav-link ${isActive("/") && !location.pathname.match(/\/\d+/) ? "active" : ""}`}
        >
          <svg className="nav-link-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
          Users
        </Link>
      </div>
    </nav>
  );
};

const App = () => {
  return (
    <BrowserRouter basename="/users">
      <div className="app-react-1">
        <AppNav />

        {/* Page Content with Routes */}
        <main className="app-content">
          <Routes>
            <Route path="/" element={<Users />} />

            {/* Nested routes for User Detail */}
            <Route path="/:userId" element={<UserDetail />}>
              <Route index element={<Navigate to="profile" replace />} />
              <Route path="profile" element={<UserProfile />} />
              <Route path="activity" element={<UserActivity />} />
              <Route path="permissions" element={<UserPermissions />} />
              <Route path="settings" element={<UserSettings />} />
            </Route>
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  );
};

export default App;
